# Aprendendo_try_and_except
 Nessa atividade, fiz uma função tentar converter nome de um numero para o proprio numero e verificando se é um numero. 
